[package]
name = "seller_client"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common"}
tokio = { workspace = true }
serde_json = "1.0"
clap = { workspace = true }
uuid = { workspace = true }