[package]
name = "customer_db"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common"}
tokio = { workspace = true }
dashmap = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
serde_json = "1.0"